# Generated by Django 4.0.6 on 2022-07-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/DoctorProfilePic/docdp.jpg', null=True, upload_to='profile_pic/DoctorProfilePic/'),
        ),
    ]
